### ISSUE TITLE
*.desktop file 

### ISSUE THREAD

**Issue by tristan-k** [itkach/aard2-web#2]
How to launch aard2-web properly through the Gnome Desktop Menu Specifications?

```
[Desktop Entry]
    Name=FooCorp Painter Pro
    Exec=foocorp-painter-pro
    Icon=foocorp-painter-pro
    Type=Application
    Categories=GTK;GNOME;Utility;
```

**Comment by tomtom** [comment]
You could use something like this, I guess (you have to adapt the path):

    [Desktop Entry]
    Name=Aard2
    Exec=java -Dslobber.browse=true -jar $AARD2/aard2-web-0.7.jar $AARD2/slob/*.slob
    Terminal=true
    X-MultipleArgs=false
    Type=Application
    Categories=Utility;
    Keywords=Utility;Dictionary;

**Comment by itkach** [comment]
aard2-web is not a desktop application, so launching it via desktop menu is strange and will not give you a proper desktop app behavior. @tomtom's desktop entry would probably work - once, subsequent attempts will fail because port would be already in use. Setting up aard2-web as a service makes more sense. For example, on a systemd machine one might set up a user service like so:
```
% cat ~/.config/systemd/user/aard2.service
[Unit]
Description=Aard 2 Web Service

[Service]
Type=forking
ExecStart=/home/username/bin/aard2
Restart=on-failure
```
where start script `/home/username/bin/aard2` is something like
```
#!/bin/bash
/usr/bin/java -jar ~/Downloads/aard2-web-0.7.jar ~/Downloads/*.slob &
```

And then start/stop/restart the service with `systemctl`:
